# Site settings
title: Quartz Enterprise Job Scheduler
email: tc-oss@softwareag.com
description: A full-featured, Java-based, In-process job scheduler.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.quartz-scheduler.org" # the base hostname & protocol for your site
twitter_username: terracottatech
github_username:  quartz-scheduler
linkedin_username: terracotta
facebook_username:  Terracotta

# The "quartz-version" value is for the latest master branch series
asciidoc_attributes: &asciidoc_attributes
  quartz-version: 2.4.0-SNAPSHOT
  quartz-2.3.x-version: 2.3.1-SNAPSHOT

asciidoctor:
  attributes: *asciidoc_attributes

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - run_cmd_each_javadoc_version.rb
  - run_proofer.sh
  - azure-pipelines.yml
  - get-deps.sh
  - add-analytics.sh
  - .idea/

exclude_from_watch:
  - .idea/
  - quartz-worktree/


# Build settings
markdown: kramdown


gems:
  - jekyll-asciidoc




defaults:
  -
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      type: "drafts"
    values:
      layout: "post"
  -
    scope:
      path: "community"
      type: "pages"
    values:
      layout: "community_page"
  -
    scope:
      path: "documentation"
      type: "pages"
    values:
      layout: "docs_page"
  -
    scope:
      path: "documentation/quartz-2.x"
      type: "pages"
    values:
      layout: "docs2x_page"
      qtz_version: "2.0.2"
      qtz_javadoc_version: "2.0.2"
  -
    scope:
      path: "documentation/quartz-2.1.x"
      type: "pages"
    values:
      layout: "docs21x_page"
      qtz_version: "2.1.7"
      qtz_javadoc_version: "2.1.7"
  -
    scope:
      path: "documentation/quartz-2.2.x"
      type: "pages"
    values:
      layout: "docs22x_page"
      qtz_version: "2.2.1"
      qtz_javadoc_version: "2.2.1"
